### ISSUE TITLE
[Roadmap]: Core Features

### ISSUE THREAD

**Issue by malisipi** [malisipi/NewFlow#8]
Application needs those features before become more stable.

- [ ] Settings (Partial Frontend parts is ready however mostly undone)
- [ ] Playlist (Backend  is done.)
- [ ] Bookmarks (Not started)
- [ ] About (Just style the about page)
- [x] Comment/Next Videos next pages (Backend is mostly done)
- [ ] Search Improvements (Channels, Playlists should be listed, and next pages should be extracted.)
- [ ] Plugins (Backend is nearly done)

**Comment by k0nstruct** [comment]
Thanks for your work! Youtube's website is getting enshittified into a mess. Do you plan to allow logging into a youtube accounts for subscriptions/home feeds?

**Comment by malisipi** [comment]
> Thanks for your work! Youtube's website is getting enshittified into a mess. Do you plan to allow logging into a youtube accounts for subscriptions/home feeds?

I am planning to support importing subscriptions from YouTube accounts (if the YouTube account is sharing subscriptions publicly).

Login with your account will not be supported due to there're no viable way to do that. There're some ways however they may cause some penalties including banning your account. So I will not take the risk.

**Comment by k0nstruct** [comment]
Ok! Take your time. This is great.
